# Generated by Django 5.2.5 on 2025-08-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('source_file', models.FileField(upload_to='reconciliation/source/')),
                ('target_file', models.FileField(upload_to='reconciliation/target/')),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('matched', 'Matched'), ('unmatched_source', 'Unmatched in Source'), ('unmatched_target', 'Unmatched in Target'), ('duplicate', 'Duplicate')], max_length=20)),
                ('source_row_data', models.JSONField(blank=True, null=True)),
                ('target_row_data', models.JSONField(blank=True, null=True)),
                ('match_key', models.CharField(blank=True, max_length=255, null=True)),
                ('differences', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation_app.reconciliationjob')),
            ],
        ),
    ]
