# Generated by Django 5.2.5 on 2025-08-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationjob',
            name='created_by',
        ),
    ]
