# Generated by Django 5.2.5 on 2025-08-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0002_remove_reconciliationjob_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationjob',
            name='headers_validation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='source_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='source_record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='target_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationjob',
            name='target_record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconciliationjob',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='reconciliation/source/'),
        ),
        migrations.AlterField(
            model_name='reconciliationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationjob',
            name='target_file',
            field=models.FileField(blank=True, null=True, upload_to='reconciliation/target/'),
        ),
    ]
