# Generated by Django 5.2.5 on 2025-08-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0003_reconciliationjob_headers_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationjob',
            name='headers_validation',
        ),
    ]
