# Generated by Django 5.2.5 on 2025-08-17 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0004_remove_reconciliationjob_headers_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
