# Generated by Django 5.2.5 on 2025-08-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0006_ruleset_rulesetfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationjob',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='reconciliation_app.ruleset'),
        ),
    ]
