# Generated by Django 5.2.5 on 2025-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0007_reconciliationjob_ruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetfield',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], default='string', max_length=20),
        ),
    ]
