# Generated by Django 5.2.5 on 2025-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation_app', '0008_alter_rulesetfield_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationjob',
            name='error_message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
